#!/sbin/ext/busybox sh

/sbin/ext/busybox mount -t rootfs -o remount,rw rootfs
/sbin/ext/busybox ln -s /sbin/recovery /sbin/busybox

mount -t ext4 -o rw,nodev,noatime,nodiratime /dev/block/mmcblk0p7 /cache >> /dev/null 2>&1

ln -s /sbin/busybox /sbin/sh

start adbd
stop tvout

if [ -f /cache/recovery/command ];
then
  cp /res/keys-samsung /res/keys
  recovery-samsung
else
  echo 1 > /sbin/recovery-is-running
  recovery
fi;
